insert into DMS(KTOV,KOL,CENA,SORT,NDM)
SELECT KTOV,KOL,CENA,SORT,(SELECT MAX(NDM) FROM DMS)
FROM DMS
WHERE NDM=(SELECT MIN(NDM) FROM DMS) AND
KTOV not in (SELECT KTOV FROM DMS WHERE NDM=(SELECT MAX(NDM) FROM DMS))
