INSERT INTO DMZ (DDM, NDM, PR)
SELECT
    GETDATE(),
    ISNULL(MAX(NDM), 0) + 1,
    CASE WHEN
        COUNT(CASE WHEN PR=1 THEN 1 END) > 
        COUNT(CASE WHEN PR=2 THEN 1 END)
    THEN 2
    ELSE 1
  END
FROM DMZ;


